<?php
// $Id$

/**
 * @file Rules Admin UI
 */

define('RULES_ADMIN_PATH', 'admin/config/workflow/rules');
define('RULES_ADMIN_REACION_PATH', RULES_ADMIN_PATH . '/reaction');
define('RULES_ADMIN_SET_PATH', RULES_ADMIN_PATH . '/rule_sets');
define('RULES_ADMIN_RULE_PATH', RULES_ADMIN_PATH . '/rules');

/**
 * Implementation of hook_menu()
 */
function rules_admin_menu() {
  $items = array();
  $items[RULES_ADMIN_PATH] = array(
    'title' => 'Rules',
    'position' => 'right',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rules_admin_reaction_overview'),
    'access arguments' => array('administer rules'),
    'file' => 'rules_admin.rule_forms.inc',
  );
  $items[RULES_ADMIN_REACION_PATH] = array(
    'title' => 'Reaction rules',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );
  $items[RULES_ADMIN_REACION_PATH . '/add'] = array(
    'title' => 'Add a new reaction rule',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rules_admin_reaction_overview'),
    'access arguments' => array('administer rules'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'rules_admin.rule_forms.inc',
    'weight' => 0,
  );
  $items[RULES_ADMIN_RULE_PATH . '/%rules_config'] = array(
    'title' => 'Editing rule',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rules_admin_form_edit_rule', 5),
    'access arguments' => array('administer rules'),
    'type' => MENU_CALLBACK,
    'file' => 'rules_admin.rule_forms.inc',
  );
  $items[RULES_ADMIN_RULE_PATH . '/%rules_config/add'] = array(
    'title' => 'Editing rule',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rules_admin_form_edit_rule', 5),
    'access arguments' => array('administer rules'),
    'type' => MENU_CALLBACK,
    'file' => 'rules_admin.rule_forms.inc',
  );
  $items[RULES_ADMIN_RULE_PATH . '/%rules_config/edit/%rules_element'] = array(
    'title' => 'Editing rule',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rules_admin_edit_element', 5, 7),
    'access arguments' => array('administer rules'),
    'load arguments' => array(5),
    'type' => MENU_CALLBACK,
    'file' => 'rules_admin.rule_forms.inc',
  );
  $items[RULES_ADMIN_SET_PATH] = array(
    'title' => 'Components',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rules_admin_sets_overview'),
    'access arguments' => array('administer rules'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'rules_admin.rule_forms.inc',
    'weight' => 0,
  );
  $items[RULES_ADMIN_SET_PATH . '/add'] = array(
    'title' => 'Add a new component',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rules_admin_components_overview'),
    'access arguments' => array('administer rules'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'rules_admin.rule_forms.inc',
    'weight' => 0,
  );
  $items[RULES_ADMIN_PATH .'/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rules_admin_settings'),
    'access arguments' => array('administer rules'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'rules_admin.rule_forms.inc',
    'weight' => 1,
  );
  return $items;
}

function rules_element_load($element, $rule_name) {
  $rule = rules_config_load($rule_name);
  $i = 1;
  foreach ($rule->conditions() as $condition) {
    $i++;
    if ($i==$element) {
      return $condition;
    }
  }
  foreach ($rule->actions() as $action) {
    $i++;
    if ($i==$element) {
      return $action;
    }
  }
}